---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: api-deployment
 labels:
  name: apiDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      name: api
  template:
    metadata:
      name: nodejs-api
      labels:
        app: web
        tier: backend
        environment: dev
        lang: nodejs
        name: api
    spec:
      containers:
        - name: api
          image: waleedsamy/hello-world-expressjs-docker
          ports:
          - name: web
            containerPort: 80
