apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: infra
  labels:
    name: fluentd
spec:
  selector:
    name: fluentd
    tier: backend
  type: NodePort
  ports:
    - name: forward
      protocol: TCP
      port: 24284
      targetPort: 24284
    - name: prometheus
      protocol: TCP
      port: 24231
      targetPort: 24231
----
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
      labels:
        app: fluentd
        tier: backend
      name: fluentd
    spec:
      containers:
        - name: fluentd
          image: waleedsamy/k8s-fluentd-nodejs-winston
          imagePullPolicy: Always
          env:
            - name: FLUENTD_OPT
              value: -q
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch.infra.svc.cluster.local"
            - name: ELASTICSEARCH_PORT
              value: "9200"
          ports:
            - name: forward
              containerPort: 24284
            - name: prometheus
              containerPort: 24231
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
