apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: infra
  labels:
    name: fluentd
spec:
  selector:
    name: fluentd
    tier: backend
  type: ClusterIP
  clusterIP: None
  ports:
    - name: forward
      protocol: TCP
      port: 24224
    - name: prometheus
      protocol: TCP
      port: 24231
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
      labels:
        name: fluentd
        tier: backend
      name: fluentd
    spec:
      containers:
        - name: fluentd
          image: waleedsamy/k8s-fluentd-nodejs-winston:v2.1
          imagePullPolicy: Always
          env:
            - name: FLUENTD_OPT
              value: -q
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch.infra.svc.cluster.local"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/XXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXX"
            - name: SLACK_CHANNEL
              value: "production_log_errors"
            - name: KIBANA_HOST
              value: "http://kibana.internal.domain.com"
          ports:
            - name: forward
              containerPort: 24224
              hostPort: 24224
            - name: prometheus
              containerPort: 24231
              hostPort: 24231
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
