apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  namespace: infra
  labels:
    name: grafana
spec:
  rules:
  - host: grafana.traffics.de
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: infra
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: infra
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:3.1.1
        name: grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
