apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: infra
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
    app: kube-state-metrics
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics-deployment
  namespace: infra
spec:
  replicas: 1
  template:
    metadata:
      namespace: infra
      labels:
        app: kube-state-metrics
        version: "v0.3.0"
    spec:
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v0.3.0
        ports:
        - containerPort: 8080
